### ISSUE TITLE
What is a prize in this challenge?

### ISSUE THREAD

**Issue by sunpietro** [Metroxe/one-html-page-challenge#5]
Is it only for fun?

**Comment by Metroxe** [comment]
It is only for fun. I have had the idea of making a prize and putting a time limit, but havn't officially done anything. I kinda want to see the reception first.

Thanks for inquiring!

**Comment by LeaVerou** [comment]
> I kinda want to see the reception first.

Doesn't the reception depend on whether there's a prize though?
