### ISSUE TITLE
Remove Sponsor

### ISSUE THREAD

**Issue by Metroxe** [Metroxe/one-html-page-challenge#50]
I thought it was cool when Github released Sponsors and thought I would put it in, but in retrospect it feels tacky and I'm not really looking to make money off the project. So I'd rather just remove it to keep things a bit cleaner.

This involves...
- [ ] removing the Sponsor tag on Github in the repository settings (@Metroxe must do this last as to not create broken links)
- [ ] removing the sponsor entry in the `entries.js`
- [ ] remove references to it on the `index.html`
- [ ] remove the `.github` directory

**Comment by lailahgrant** [comment]
Hello please, Could I try this?
It is solid new, I don't get it but trying this with your help will give me exposure. 
Thanks.

**Comment by girolamodaschio** [comment]
Hi there, I found this issue still open so I've tried to fix.

**Comment by Metroxe** [comment]
Thank you!
